version: "3"
services:

  shiny:
    build: .
    expose:
      - 3838
    volumes:
      - ./apps/:/srv/shiny-server/
      - ./shiny_logs/:/var/log/shiny-server/

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
